import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero.js'
import Ready from '../components/Ready.js'
import Features from '../components/Features.js'
import About from '../components/About.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AutoML</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.svg" />
      </Head>
      <Hero />
      <Features />
      <About />
      <Ready />
    </div>
  )
}
